### ISSUE TITLE
Cannot change css of mAvatar

### ISSUE THREAD

**Issue by galex** [cfnz/muirwik#14]
Hello,

When I write the following:
```
mAvatar(src = state.avatarPath, alt = "Reptile", className = "blabla") {
    css {
        margin(2.spacingUnits)
        width = 60.px
        height = 60.px
    }
}
```
The react component gets a default generated className without relation to my css configuration:
```
{
  "alt": "User Avatar",
  "src": "/images/alex.jpg",
  "className": "MuiAvatar-img-1238"
}
```
Any idea what is going on?

Regards,
Alex

**Comment by cfnz** [comment]
Do you mean it does not pick up the className = blabla or the css in code?

**Comment by cfnz** [comment]
Just having a look at some of the old issues... just tested this and the className was included, so may have got fixed somewhere along the line... so closing :-)
