### ISSUE TITLE
'default' color of Typography no longer available

### ISSUE THREAD

**Issue by karol-202** [cfnz/muirwik#15]
'default' color of Typography component has been replaced with 'initial' in [this commit](https://github.com/mui-org/material-ui/commit/aa196b41bf1220407334e7ee5023c77e39dbdc05#diff-43516e8a45efd62c08162a16a62a73f6)

Using 'default' generates following warning:
`Warning: Failed prop type: Invalid prop 'color' of value 'default' supplied to 'ForwardRef(Typography)', expected one of ["initial","inherit","primary","secondary","textPrimary","textSecondary","error"].`

**Comment by cfnz** [comment]
Thanks for the pull request.
Just wondering what version of Material UI you are running against? Is it version 4.something?

The current build of Muirwik is against 3.9.1... I imagine there might be quite a few changes needed to go to 4, but I have not tested that yet... maybe there is not as much as I first thought (especially if you are running against 4.something and things are mostly working :-) )...

I have got a few changes still to push for version 3.9.3, so will have a look at pulling in your change when I get to 4 :-)

**Comment by karol-202** [comment]
Oh, I forgot to mention that I'm using Material UI 4.1.3.
I have used only a few components for now and everything (excluding this issue) was working well, so maybe it won't be so hard to port it to v4.

I liked this library (as far as I know, this is the only working MUI binding for Kotlin/JS) and I would like to contribute. But this is my first touch with React, Material UI and JS world at all, so for now I will be filling issues if I find one and doing some pull requests for them if they are simple enough like this one.

**Comment by cfnz** [comment]
Cool, that explains it.

I will close this issue for now as it relates to version 4. When we move to 4.x there will probably be quite a few warnings to fix... so I will use your pull request then :-). Also, thanks for the update on using v4 reasonably OK... might look at the move to 4 sooner.

Muirwik was my first touch with React, JS, npm, webpack, etc too :-)... was a big learning curve (though I  think I am still on the incline :-) ).
