### ISSUE TITLE
How to use it in react-kotlin project?

### ISSUE THREAD

**Issue by THEAccess** [cfnz/muirwik#19]
Hello,
I have a react kotlin project with npm for dependencies and build.
Normally, i install dependencies like this 
`
    npm i  @jetbrains/kotlin-styled
`
`
    npm run gen-idea-libs
`
However, i have not set up gradle and don't know how to do it.
How can i  add this great library? Any help is appreciated.

**Comment by cfnz** [comment]
Hi there,

Gradle setup is pretty easy as the source comes with a gradlew shell script or bat file for windows that pulls down all that Gradle needs... so you actually don't need to install Gradle as such, it does it all for you.

I just tested following my instructions on the git project home page (in Linux) and found that the last line was a bit out of date... so I have just updated the README.md and cloning into a new PC works as expected.

For Windows, I have not tested it, but you should be able to swap ./gradlew for gradlew.bat, though at some stage I think the last step also had a problem, it showed the webpack command that it tried to run and failed, however running that same command directly on the command line worked. I shall try running on a Windows box a bit later, but hopefully that should get you going for now (hopefully :-)).

**Comment by cfnz** [comment]
Tested in windows, and there was an issue - my gradle webpack plugin needed to be updated to run the Windows specific webpack commands... tested and working now.
