### ISSUE TITLE
Styles from styled don't apply

### ISSUE THREAD

**Issue by krupt** [cfnz/muirwik#23]
The code below:
```
mButton("Click me!", MColor.primary, MButtonVariant.contained) {
    css {
        margin = "25px"
    }
}
```
compiles to:
```
<button class="MuiButtonBase-root MuiButton-root MuiButton-contained sc-AxirZ dcxuZU MuiButton-containedPrimary" tabindex="0" type="button" _css="margin: 25px;">
    <span class="MuiButton-label">Click me!</span>
    <span class="MuiTouchRipple-root"></span>
</button>
```
Class .MuiButtonBase-root overrides class .dcxuZU, which contains margin 25px

What do I do wrong? I think class .dcxuZU should be at the begging of button's class attribute.

**Comment by cfnz** [comment]
Hi there, at a guess, I would say you need to look into the order of the css files being injected into index.html... this is related to styled jss...

Make sure you are using the mStylesProvider something like this:
```
fun main(args: Array<String>) {
    render(document.getElementById("root")) {
        mStylesProvider("jss-insertion-point") {
            app()
        }
    }
}
```
Then in your index.html, have the same comment as used above just above the <\head>.

This is supposed to make styles jss insert the styles from code as you have it, below the main css imports of material design.
```
<head>
    ...other code...
    <!-- jss-insertion-point -->
</head>
```
When looking at the source of the rendered page, hopefully you will see something like
```
...other style definitions...
<style data-jss="" data-meta="MuiListItemText">...code...</style>
<style data-styled="" data-styled-version="4.4.1">... your css code...</style>
```

**Comment by krupt** [comment]
Thanks a lot. It works
