### ISSUE TITLE
MSelect should extend from MInput

### ISSUE THREAD

**Issue by pablisco** [cfnz/muirwik#26]
In Material-UI Select extends from Input however, the mapping `MSelectProps` doesn't extend from `MInputProps`. This means that options like `disableUnderline` is not available.

The workaround for this is to define it like this:

```kotlin
attrs.asDynamic().disableUnderline = true
```
Not ideal as it reduces discoverability. 

An easy fix would be to have `MSelectProps` extend from `MInputProps`

This could be affecting other Form elements but I haven't tested them.

**Comment by cfnz** [comment]
Main reason it wasn't is that SelectProps has different onChange params which kotlin doesn't like.

Released version has introduced an extra prop interface layer to make things better... disableUnderline should now be a normal prop.
