### ISSUE TITLE
Error: Can't resolve 'kotlin-css-js'

### ISSUE THREAD

**Issue by IARI** [cfnz/muirwik#28]
I included the following in the gradle dependencies of my kotlin.js react project:

```kotlin
    implementation("com.ccfraser.muirwik:muirwik-components:0.4.1")
    implementation(npm("@material-ui/core"))
```
So far - not using anything - the project runs and the page loads
As soon as I try to use a material ui component somewhere inside my app - for example like this:
```kotlin
mTextField("User")
```
The app isn't rendered anymore (not even the errorboundary wrapping the whole app catches anything) and I get this error:

> ERROR in D:/github/logoleon-backend/build/js/packages_imported/muirwik-components/0.4.1/muirwik-components.js
> Module not found: Error: Can't resolve 'kotlin-css-js' in 'D:\github\logoleon-backend\build\js\packages_imported\muirwik-components\0.4.1'
>  @ D:/github/logoleon-backend/build/js/packages_imported/muirwik-components/0.4.1/muirwik-components.js 14636:558-582
>  @ ./kotlin/logoleon-backend-logoleon-manager.js
>  @ multi ./kotlin/logoleon-backend-logoleon-manager.js

**Comment by cfnz** [comment]
I have not used the npm gradle way of adding js dependencies much, rather have used package.json. I was going to take a more serious look at it at some stage but somewhere someone mentioned it still had a few issues to sort out, so I left it using package.json and webpack.config.js manually.

It could be that the gradle npm method does not pick up all the required dependencies.

You could have a look at the test apps package.json and see if anything there helps out, or just use the package.json method like the test app.

**Comment by cfnz** [comment]
You could see if adding any of these dependencies help (version numbers might be incorrect)...
```
        implementation(npm("@jetbrains/kotlin-react", "16.9.0-pre.89"))
        implementation(npm("@jetbrains/kotlin-react-dom", "16.9.0-pre.89"))
        implementation(npm("@jetbrains/kotlin-css", "1.0.0-pre.89"))
        implementation(npm("@jetbrains/kotlin-css-js", "1.0.0-pre.89"))
        implementation(npm("@jetbrains/kotlin-styled", "1.0.0-pre.89"))
```

**Comment by cfnz** [comment]
Decided to spend some time looking into the new build process... It does simplify things, but not sure if it is slower... also has some issues, e.g. peer dependencies, but it does work.
Will do an updated release soon (today or tomorrow... hopefully).

**Comment by cfnz** [comment]
Hopefully the latest version closes this issue and doesn't raise any new ones.
New build type seems the way of the future, so have tried to embrace it.
