### ISSUE TITLE
Improvement for String.toHyphenCase() (Base.kt)

### ISSUE THREAD

**Issue by mice777** [cfnz/muirwik#31]
One-liner:
```
fun String.toHyphenCase() =
    split(Regex("(?=[A-Z])")).filter(String::isNotEmpty).joinToString("-", transform = String::toLowerCase)
```

**Comment by cfnz** [comment]
About a year later... had to make a tweak in the function which reminded me of this issue, the current method works and works faster, so will leave it as is for now (even though it is uglier :-) ).
