### ISSUE TITLE
Improve usage of icons

### ISSUE THREAD

**Issue by krzema12** [cfnz/muirwik#32]
I'm in the middle of [replacing my custom Material UI typings/wrappers](https://github.com/krzema12/fsynth/commit/49c8aca4ca074ecc23520aa83a3fa869833164c8) in my pet project (https://github.com/krzema12/fsynth), and noticed several problems with using icons:

1. For icons to work, one has to add this piece to the `<head>` section of their HTML: `<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">`. Without it, icons are replaced with their names cropped to the button's size. This approach is problematic because:
  * it's not included in the docs, and it's just another implicit dependency to add. It took me a while to find it, and I found it by looking at the test app (thanks for it!)
  * it makes another web call which in some circumstances may not be possible (running the app offline) or slow (slow Internet connection)
2. Names of icons accepted by `mIcon` and `mIconButton` are just strings. It's not clear what naming convention is used (it's e.g. `play_arrow`, not `PlayArrow` [as presented on Material UI website](https://material-ui.com/components/material-icons/)). It's also prone to typos.

I recommend making the usage of icons more type-safe and self-contained. Adding `implementation(npm("@material-ui/icons", "4.9.1"))` may still be needed, but at least we can get rid of including the font. There's an alternative way of using icons, without fonts: as regular components. See e.g. https://github.com/krzema12/fsynth/blob/master/web/src/main/kotlin/it/krzeminski/fsynth/typings/materialui/icons/PlayArrowIcon.kt.

I'm keen to prepare some pull request in my spare time. If you have any thoughts on this, let's discuss it :)

**Comment by cfnz** [comment]
Yes, the icons are using the less desirable font based approach of [Material-UI icons](https://material-ui.com/components/icons/).

The main reason for this is at the time I was looking at it, there were 100s of icon files that would need to be imported. Ducat wasn't around then, maybe it can be used now? Or perhaps there could be another automated way of generating all the files, but at the time I wasn't up to it, and using the font icons worked OK :-)

In terms of 2, the naming convention, I think Material-UI just uses the [Material IO names](https://material.io/resources/icons/).

And yes, happy to have help improving things :-).

**Comment by krzema12** [comment]
Ok, I propose the following steps, roughly mapped 1:1 to commits/PRs:

1. Add a new API for creating `mIcon` and `mIconButton` that accepts a custom type instead of a string with icon name. The type will be probably a sealed class with all known icons as its objects, but also with a way to use an icon that is not present, given its name as string. Thanks to this, if a new icon appears, one will be able to use this generic API without waiting for a new version of muirwik. The current API with accepting strings will be marked as deprecated and removed whenever you find appropriate (not in scope of this issue). Under the hood, still use the font approach. Hardcode all known icon names - no smart generation of any code yet.
2. Change the underlying implementation from font approach to component approach. No muirwik API changes should be required. Still no generation of code.
3. Add a build step to generate any needed code, so that all icons present in `@material-ui/icons` appear as possible values of the custom type. `@material-ui/icons` in some chosen version will be added as a build-time dependency and the build logic will extract the names from there. 

Let me know if it makes sense to you.

**Comment by cfnz** [comment]
Thanks for that.

In terms of changing mIcon, I am thinking it will be best to closely follow the Material-UI way of doing things. Currently their Icon takes a string child as the name of the icon, so I think we should leave mIcon the way it is and introduce something new. That way everything keeps working, new icons can be added easily and it follows Material UI’s Icon component.

Muirwik does not have an SVG icon whereas Material-UI does. So I have added mSvgIcon which is similar in use to the Material UI SvgIcon (will release it soon). In Material-UI all the other icons take on the same props as SvgIcon (or uses SvgIcon to create their icon).

Material-UI has over 5,000 icon files (including versions for Outlined, Rounded, Sharp, etc), each as a separate component. I think this helps with code splitting. So we need to decide if we are going to auto generate 5000 kotlin files, or do it some other way. The Kotlin dead code elimination might mean we don’t need a file for each icon, but having one in each file might still help with code splitting/DCE and it is a bit more like Material-UI. Then we would have things like mAccessAlarmIcon, etc (etc, etc, etc, etc...).

So I think this is the bigger task, having the build create the appropriate files, however many they may be.

**Comment by Cottand** [comment]
@cfnz thanks for the amazing wrapper!

Just wanted to mention here for visibility that the icons currently present as fonts do not include all of the icons the original library has as components (`Github`, `Apple` or `LinkedIn`, for example)

**Comment by cfnz** [comment]
That is correct, the implementation uses the Material UI font icons though you can use other icon fonts such as Font Awesome as explained in the Material UI docs. (I haven't tried it, but Font Awesome has the Github, Apple and LinkedIn icon for example).

The reason why the SvgIcon's from Material UI are not all included is that there are thousands of them (over 5.5K js files in the material UI icons folder). I did do a build took that scanned this directory and created a kotlin file for each js icon file, but the build took 15 or 20 minutes (or something like that, it was a while ago...), so left that to think about at some future stage...

So if you need those icons, you could give Font Awesome a go, or perhaps create an mSvgIcon with the path info from the icon you want (I did also look at this approach, though some icons are a bit more complicated, and I am not sure on the licencing of doing such...).

**Comment by Cottand** [comment]
I went for mSvgIcon and had great results. I borrowed the path from [here](https://materialdesignicons.com/). The license is permissive enough.
