### ISSUE TITLE
mBackdrop not working (missing open prop)

### ISSUE THREAD

**Issue by JWood48** [cfnz/muirwik#33]
I'm trying to use the mBackdrop component, but get this error:

```
react_devtools_backend.js:2273 Warning: Failed prop type: The prop `open` is marked as required in `ForwardRef(Backdrop)`, but its value is `undefined`
```

The open property seems to be required here: https://material-ui.com/api/backdrop/

**Comment by cfnz** [comment]
Should be fixed in latest version 0.5.2 which includes an an example in the test app.
