### ISSUE TITLE
Question: how to import it via gradle

### ISSUE THREAD

**Issue by christian-draeger** [cfnz/muirwik#36]
is this released somewhere? if so how to import it as a gradle dependency?

**Comment by christian-draeger** [comment]
ok i guess i found it by the help of google:
`implementation("com.ccfraser.muirwik:muirwik-components:0.5.1")`

maybe this should be added to the readme? ^^

**Comment by cfnz** [comment]
The best way to get started is to use the separate [starter app](https://github.com/cfnz/muirwik-starterapp).
I have updated the readme.md to make this a bit clearer.
