### ISSUE TITLE
localization support

### ISSUE THREAD

**Issue by chipnesh** [cfnz/muirwik#39]
Are there any plans for localization support?
I wanted to pass a locale to the `createMuiTheme` function but it doesn't have args parameter.
Maybe there is a workaround to do this?

**Comment by cfnz** [comment]
Agree that it will be good if it did... I shall have a look in the next couple of days.

**Comment by cfnz** [comment]
Localization support added as per Material-UI. Added a simple page to the test app to show its workings.

**Comment by chipnesh** [comment]
Thanks!
How soon it will be available at maven central?

**Comment by cfnz** [comment]
Just published it and seems to be there now.
