### ISSUE TITLE
Support for more experimental components (e.g. Timeline)

### ISSUE THREAD

**Issue by krzema12** [cfnz/muirwik#43]
Hi,

are you generally open to wrapping more components from the Lab? I see that e.g. [Alert](https://github.com/cfnz/muirwik/blob/master/muirwik-components/src/main/kotlin/com/ccfraser/muirwik/components/lab/alert/Alert.kt) is in muirwik.

In particular, I'm interested in https://material-ui.com/components/timeline/. I can send a PR that adds support for it, I just wanted to ensure it's OK with you :) In theory experimental components can have less stable APIs.

**Comment by cfnz** [comment]
Yes, now that we have one, I can't see why we can't add other Lab components... so happy to receive PR's

**Comment by krzema12** [comment]
Thanks! Will post a PR once I reach a point in my project where I need the experimental components :)
