### ISSUE TITLE
mAppBar(elevation = 0) elevation - doesn't exists

### ISSUE THREAD

**Issue by theromis** [cfnz/muirwik#53]
trying to follow theme examples, one on nice features is "flat" toolbar, unfortunately can't find binding for it.

**Comment by cfnz** [comment]
You are right... AppBarProps should have inherited from PaperProps.

This was a quick fix, so I released it. You can get it with the latest version and then by attrs.elevation... eg.:
```
mAppBar(position = MAppBarPosition.static) {
    attrs.elevation = 0
    mToolbar {
        mIconButton("menu", color = MColor.inherit) { css { marginLeft = -12.px; marginRight = 20.px }}
        mToolbarTitle("Flat (elevation = 0)")
        mIconButton ("account_circle", color = MColor.inherit )
    }
}
```

**Comment by theromis** [comment]
@cfnz thank you for quick fix
