### ISSUE TITLE
default Material-UI control Margin on FormControls

### ISSUE THREAD

**Issue by sirakuzovsky** [cfnz/muirwik#54]
MFormControlMargin.none is default by Material-UI, not MFormControlMargin.normal 
[see official docs](https://material-ui.com/ru/api/form-control/)

**Comment by cfnz** [comment]
In mFormControl it defaulting to none. Are you referring to its use in mTextField?

**Comment by sirakuzovsky** [comment]
Yes, on mTextField 
               mGridItem(xs = MGridSize.cells12, sm = MGridSize.cells6) {
                    **mTextField**(
                        required = true, /*value = city,*/ name = "city", label = "City", fullWidth = true,
                        autoComplete = "shipping address-level2", **margin = MFormControlMargin.none**
                    )
                }

**Comment by cfnz** [comment]
That is a nuisance... you are right, it should have been none (or null)... If I change it now it may break existing layouts (it made a bit of a mess of the test app), so I might change it in a bigger breaking change version... maybe even with the rollout of version 5. So will leave this open till then...

**Comment by cfnz** [comment]
Version 5 has been merged to master and does not have this issue.
