### ISSUE TITLE
immutable grid item element style

### ISSUE THREAD

**Issue by sirakuzovsky** [cfnz/muirwik#57]
Hi! I try to customize padding on mGridItem, but I can't. Think, there is no way doing this from Kotlin code, cause default MuiGrid style's has a major priority and code like this change nothing 
```
mGridItem {
    css{paddingRight = 0.spacingUnits}
    attrs.xs = MGridSize.cells7
}
```

**Comment by cfnz** [comment]
Sometimes Material UI's styling is more specific than the css generated as in your example.
One way around it is to apply a style to the mGridItem which is then more specific than Material UI's styling...
e.g.
```            
mGridItem(xs = MGridSize.cells6) {
    attrs.asDynamic().style = CSSBuilder().apply { paddingRight = 0.px }.toStyle()
    // Grid content
}
```

**Comment by sirakuzovsky** [comment]
Oh, thanks!
