### ISSUE TITLE
Add Autocomplete Component

### ISSUE THREAD

**Issue by lammertw** [cfnz/muirwik#58]
The Autocomplete Component would be a useful addition:
https://material-ui.com/components/autocomplete/

**Comment by cfnz** [comment]
I agree... added in latest commit :-)
Note: Not fully tested, there are lots of props to play with, but basic usage as shown in test app is working.

**Comment by lammertw** [comment]
Thanks, is it possible to publish the latest version? It seems that the latest published version is still 0.6.7.

**Comment by cfnz** [comment]
Published a while ago (now on Maven Central)
