### ISSUE TITLE
Bintray seems to be dead

### ISSUE THREAD

**Issue by night-crawler** [cfnz/muirwik#60]
Hi there! My build pipelines died:

```bash
* What went wrong:
Could not determine the dependencies of task ':packageJson'.
> Could not resolve all dependencies for configuration ':npm'.
   > Could not resolve com.ccfraser.muirwik:muirwik-components:0.4.1.
     Required by:
         project :
      > Could not resolve com.ccfraser.muirwik:muirwik-components:0.4.1.
         > Could not get resource 'https://dl.bintray.com/cfraser/muirwik/com/ccfraser/muirwik/muirwik-components/0.4.1/muirwik-components-0.4.1.pom'.
            > Could not GET 'https://dl.bintray.com/cfraser/muirwik/com/ccfraser/muirwik/muirwik-components/0.4.1/muirwik-components-0.4.1.pom'. Received status code 403 from server: Forbidden

```

AFAIK everything must be moved to maven.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by cfnz** [comment]
I am in the process of moving to Maven via sonatype (probably), but I understood that jcenter would continue to be operational in a read only manner for another month or two. Looking at their website now, it actually looks like they have decided to keep jcenter going (but read only) for longer now.

But it looks like you have a dependency on bintray which used to be the staging area before publishing to jcenter, so (for current and older versions at least) if you remove your repository for bintray and use the jcenter one instead, you should hopefully be good to go. (e.g. jcenter repository shown at mvnrepository.com: https://mvnrepository.com/artifact/com.ccfraser.muirwik/muirwik-components).

**Comment by night-crawler** [comment]
> if you remove your repository for bintray and use the jcenter one instead, you should hopefully be good to go.

It worked, thank you. :)
