### ISSUE TITLE
Replace JCenter repository

### ISSUE THREAD

**Issue by jpink** [cfnz/muirwik#62]
The RepositoryHandler.jcenter() method has been deprecated. This is scheduled to be removed in Gradle 8.0. JFrog announced JCenter's shutdown in February 2021. Use mavenCentral() instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.0.2/userguide/upgrading_version_6.html#jcenter_deprecation

**Comment by cfnz** [comment]
Moved to Maven Central a couple of releases ago
