### ISSUE TITLE
Is js(LEGACY) still needed?

### ISSUE THREAD

**Issue by sentinelweb** [cfnz/muirwik#64]
Looks like it might be as this looks recent -  https://github.com/cfnz/muirwik/issues/35

i am having issue with the LEGACY flag enabled have just updated all 

```
ver_kotlin_react=17.0.2-pre.208-kotlin-1.5.10
ver_kotlin_styled=5.3.0-pre.208-kotlin-1.5.10
ver_kotlin=1.5.10
implementation("org.jetbrains.kotlin-wrappers:kotlin-react:$ver_kotlin_react")
implementation("org.jetbrains.kotlin-wrappers:kotlin-react-dom:$ver_kotlin_react")
implementation("org.jetbrains.kotlin-wrappers:kotlin-styled:$ver_kotlin_styled")
```
as i was getting :
```
Module not found: Error: Can't resolve 'kotlin-wrappers-kotlin-extensions-js-legacy' in '/Users/***/repos/personal/cuer/cuer/build/js/packages/Cuer-remote/kotlin-dce-dev'

Module not found: Error: Can't resolve 'kotlin-wrappers-kotlin-styled-js-legacy' in '/Users/***/repos/personal/cuer/cuer/build/js/packages/Cuer-remote/kotlin-dce-dev'

Module not found: Error: Can't resolve 'kotlin-wrappers-kotlin-react-js-legacy' in '/Users/***/repos/personal/cuer/cuer/build/js/packages/Cuer-remote/kotlin-dce-dev'
```

Looking in the webpack packages directory there were no js files for those legacy modules

So i copied `muirwik-components` to my project and just removed the LEGACY in js(LEGACY)
 - also updated to the same libs i was using (but that could also be done with an exclude).
`/muirwik-components/build.gradle.kts` is here https://github.com/sentinelweb/cuer/blob/feature/130_make_shared_kmp_module_remote1/muirwik-components/build.gradle.kts

Obviously not a long term solution but it looks like the js-legacy thing is in flux at the moment

**Comment by cfnz** [comment]
I see you are using 1.5.10... I backed off this as I had issues, and everything worked fine on 1.5.0 so thought I would push the combined LEGACY and IR (i.e. js(BOTH)) to master on version 1.5.0.

I have not had a look yet at 1.5.10 again to see what the issues were.

Also, I see you are using Muirwik 0.7.0... 0.8.0 is the first (and latest) version that works properly (as far as I can tell) with js(LEGACY) and js(IR).

**Comment by sentinelweb** [comment]
yeah strange that 1.5.10 has the legacy issues... i tried it and got them ...

i switched back to 1.5.0 and used muirwik 0.8.0 and it seems to work fine ...

Great work on it all btw ... the library is amazing ....
