### ISSUE TITLE
Support for Material UI 5

### ISSUE THREAD

**Issue by krzema12** [cfnz/muirwik#72]
Any plans to support https://github.com/mui-org/material-ui/releases/tag/v5.0.0? :smile: We are looking at using Muirwik in our company-internal project and I'm wondering if we can count on keeping up with newest Material UI version.

For the record, as of now, the latest available 4.x version is [4.12.1](https://github.com/mui-org/material-ui/releases/tag/v4.12.3) and Muirwik now uses [4.11.4](https://github.com/cfnz/muirwik/blob/3a9a231f74bfa124cece029b46353a58f581d09e/muirwik-components/build.gradle.kts#L25).

**Comment by cfnz** [comment]
Muiwik reverted to version 4.11.4 as there was a breaking change (see issue #67).

In terms of version 5, I have a branch that compiles and semi works with version 5.0.1 but the change in the styling system has caused some issues, and there are still a few things to change/update, so it is still a work in progress.

**Comment by gad2103** [comment]
What branch? And do you need help with this? I would love to use the wrapper library but need v5

**Comment by gad2103** [comment]
I have also been looking at this repo and talking to the owner https://github.com/turansky/mui-kotlin

Maybe there's room for collaboration to move this along quicker?

**Comment by cfnz** [comment]
Version 5 branch was released some time ago, but just now merged into Master.
Also check out possible retirement note on Muirwik in the readme.
